# Generated by Django 5.1.5 on 2025-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_studentfeesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeesrecord',
            name='balance_payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentfeesrecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
