# Generated by Django 4.2.9 on 2025-05-16 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffs', '0007_studentfeesrecord_balance_payable_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfeesrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staff Stu-Fees Record'},
        ),
        migrations.AlterField(
            model_name='staffattendancerecord',
            name='staff',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
