# Generated by Django 4.2.9 on 2025-05-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0008_alter_studentfeesrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeesrecord',
            name='hidden_by_principal',
            field=models.BooleanField(default=False),
        ),
    ]
