# Generated by Django 4.2.9 on 2025-06-20 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0009_studentfeesrecord_hidden_by_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequeststaff',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequeststaff',
            name='leave_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
