# Generated by Django 4.2.9 on 2025-06-21 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0010_leaverequeststaff_is_emergency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequeststaff',
            options={'ordering': ['-date_applied']},
        ),
        migrations.RenameField(
            model_name='leaverequeststaff',
            old_name='leave_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='leaverequeststaff',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaverequeststaff',
            name='reason',
            field=models.TextField(default=django.utils.timezone.now),
        ),
    ]
