# Generated by Django 4.2.9 on 2025-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0011_alter_leaverequeststaff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequeststaff',
            name='reason',
            field=models.TextField(),
        ),
    ]
