# Generated by Django 4.2.9 on 2025-06-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0012_alter_leaverequeststaff_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequeststaff',
            name='send_to_principal',
            field=models.BooleanField(default=False),
        ),
    ]
