# Generated by Django 5.1.5 on 2025-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_attendancerecord_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stureportcard',
            name='date',
            field=models.DateField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='parent_signature',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
