# Generated by Django 5.1.5 on 2025-05-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_hiddennotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.payment'),
        ),
    ]
