# Generated by Django 5.0.7 on 2025-05-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_staffnotification_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffnotification',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='staffnotification',
            name='student',
        ),
        migrations.DeleteModel(
            name='HiddenNotification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='StaffNotification',
        ),
    ]
