# Generated by Django 5.1.5 on 2025-05-06 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_studentfeesrecord'),
        ('students', '0013_staffnotification_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fees_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffs.studentfeesrecord'),
        ),
    ]
