# Generated by Django 4.2.9 on 2025-05-16 11:32

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0014_payment_fees_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='parent_signature',
            field=ckeditor.fields.RichTextField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='signature_class_teacher',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='signature_principal',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='student',
            field=models.ForeignKey(limit_choices_to={'userprofile__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='term',
            field=models.CharField(choices=[('Term I', 'Term I'), ('Term II', 'Term II'), ('Term III', 'Term III')], default='', max_length=10),
        ),
    ]
