# Generated by Django 5.0.7 on 2025-05-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_payment_fees_record'),
        ('students', '0014_remove_payment_user_remove_staffnotification_amount_and_more'),
    ]

    operations = [
    ]
