# Generated by Django 4.2.9 on 2025-05-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_attendancerecord_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stureportcard',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stureportcard',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('absent', 'Absent')], max_length=10),
        ),
    ]
