# Generated by Django 4.2.9 on 2025-05-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_stureportcard_total_marks_alter_stureportcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stureportcard',
            name='all_subject_mark',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
