# Generated by Django 5.0.7 on 2025-05-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffattendancerecord',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffAttendanceRecord',
        ),
    ]
