# Generated by Django 5.1.5 on 2025-05-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal_studentfeesrecord',
            name='created_by',
            field=models.CharField(choices=[('staff', 'Staff'), ('principal', 'Principal')], default='principal', max_length=20),
        ),
    ]
