# Generated by Django 4.2.9 on 2025-05-30 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0003_circulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationReadHide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('circulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.circulation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'circulation', 'role')},
            },
        ),
    ]
